In [1]:
#librerías de keras
from keras.models import Sequential
from keras.layers import Convolution2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense

#preprocesamiento de imagen
from keras.preprocessing.image import ImageDataGenerator

C:\Users\Usuario\Anaconda3_64\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
#carga modelo
from joblib import dump, load
classifier = load('./Model_TF1_13_1/10-classifier_1_13_1.joblib')

In [3]:
def getPredict(clase,stepsClase):
    test_datagen = ImageDataGenerator(rescale = 1./255)
    test_set = test_datagen.flow_from_directory('2. Dataset_Imágenes_No Vacías/trainingSet',
                                                target_size = (64, 64),
                                                batch_size = 32,
                                                classes=[clase],
                                                class_mode = 'categorical')
    resultClase=classifier.predict_generator(test_set,steps=stepsClase)
    return resultClase

In [4]:
#prueba modelo batch
import numpy as np

array=['Bird','Cat','Dog','Fish','Flower','Food','Person','Reptil','Tree','Utensil']
numClass=len(array)
Results=np.zeros((numClass,numClass), dtype=np.int64)
print(Results[0])
k=0
for clase in array:
    resultClase=getPredict(clase,10)
    print(clase)
    #print(resultClase)
    print(len(resultClase))
    for i in range(len(resultClase)):
        may=0
        pos=0
        for j in range(len(resultClase[i])):
            #print(resultClase[i][j])
            if resultClase[i][j]>may:
                pos=j
                may=resultClase[i][j]
        Results[k][pos]+=1
        #print(pos)
    #print(Results[k])
    k+=1
print('Matriz de confusión:')
print(Results)

[0 0 0 0 0 0 0 0 0 0]
Found 1308 images belonging to 1 classes.
Bird
320
Found 1044 images belonging to 1 classes.
Cat
320
Found 824 images belonging to 1 classes.
Dog
320
Found 742 images belonging to 1 classes.
Fish
320
Found 751 images belonging to 1 classes.
Flower
320
Found 1067 images belonging to 1 classes.
Food
320
Found 844 images belonging to 1 classes.
Person
320
Found 705 images belonging to 1 classes.
Reptil
320
Found 60 images belonging to 1 classes.
Tree
300
Found 894 images belonging to 1 classes.
Utensil
320
Matriz de confusión:
[[281   4   5   4   4   3   5   7   0   7]
 [ 24 227   7   8   6   9  14   8   0  17]
 [ 28   6 226   8   8   3  14  14   0  13]
 [ 28   2   2 244   3   9   6   9   0  17]
 [  6   0   0   0 308   4   0   1   0   1]
 [  0   0   0   4   7 308   0   0   0   1]
 [  9   1   3   6   2   4 273   6   1  15]
 [ 17   2   5   9  12   7   4 253   0  11]
 [ 10   0   0  10  35  15   0   0 230   0]
 [ 10   1   4   3   1   5   8   5   0 283]]


In [5]:
#matriz de confusión
Precision=np.zeros((numClass,1), dtype=np.float64)
Recall=np.zeros((numClass,1), dtype=np.float64)
F1SCORE=np.zeros((numClass,1), dtype=np.float64)

AvgF1=0
AvgP=0
print('Métricas','clase',':','Precision', 'Recall','F1SCORE')
for  i in range(numClass):
    TP=Results[i][i]
    TN=0
    FP=0
    FN=0
    for j in range(numClass):
        if i!=j:
            TN+=Results[j][j]
            FP+=Results[j][i]
            FN+=Results[i][j]
    P=TP/(TP+FP)
    R=TP/(TP+FN)
    Precision[i]=P
    Recall[i]=R
    F1SCORE[i]=(2*P*R)/(P+R)
    print('Métricas',array[i],':',Precision[i], Recall[i],F1SCORE[i])
    AvgF1+=F1SCORE[i]
    AvgP+=P
    
#eficiencia de modelo
print("Efciencia:\n\n")
AvgF1=AvgF1/numClass
print('Average F1-Score:',AvgF1*100,'%')

AvgP=AvgP/numClass
print('Mean Average Precision:',AvgP*100,'%')

Métricas clase : Precision Recall F1SCORE
Métricas Bird : [0.68038741] [0.878125] [0.76671214]
Métricas Cat : [0.93415638] [0.709375] [0.80639432]
Métricas Dog : [0.8968254] [0.70625] [0.79020979]
Métricas Fish : [0.82432432] [0.7625] [0.79220779]
Métricas Flower : [0.79792746] [0.9625] [0.87252125]
Métricas Food : [0.83923706] [0.9625] [0.89665211]
Métricas Person : [0.84259259] [0.853125] [0.84782609]
Métricas Reptil : [0.8349835] [0.790625] [0.81219904]
Métricas Tree : [0.995671] [0.76666667] [0.86629002]
Métricas Utensil : [0.77534247] [0.884375] [0.82627737]
Efciencia:


Average F1-Score: [82.77289913] %
Mean Average Precision: 84.21447579678964 %
